title: GNU Linux Users' Group, NIT Durgapur
email: your-email@example.com
description: > # Needs to changed
  Official website of GNU Linux Users' Group, NIT Durgapur
baseurl: "https://lugnitdgp.github.io"
url: ""
twitter_username: jekyllrb
github_username:  lugnitdgp

# Build settings
markdown: kramdown
theme: minima
future: true
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
